---
# Previously, we used overlayfs to mount the Artery repository located
# on the host machine in the virtual machine. This approach is ill-fated
# because the "lower layer" (the directory on the host machine) may change
# while being mounted as part of overlayfs in the virtual machine.
# This is not supported by overlayfs and leads to undefined behaviour.
#
# We now add the repository located on host as git remote 'vagrant' instead.
# This role can be removed in the future when no old deployments exist anymore.

- name: remove deprecated mount of overlay filesystem
  mount:
    path: "{{ ansible_user_dir }}/artery"
    src: overlay
    state: absent
  become: yes

- name: remove deprecated mount of artery-host
  mount:
    path: "{{ ansible_user_dir }}/.overlay/artery-host"
    state: absent
  become: yes
